---

- name: Download and install a custom project to Ansible Tower
  hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: Download and unpack artefact
      unarchive:
        src: "{{ artefact_url }}"
        dest: "{{ project_dir }}"
        mode: "{{ awx_user }}"
        group: "{{ awx_group }}"
        list_files: True
        remote_src: yes
      register: file_list
    - debug:
      msg: "{{ file_list }}"
