---

- name: Download and install a custom project to Ansible Tower
  hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: Download and unpack artefact
      unarchive:
        src: "{{ artefact_url }}"
        dest: "{{ project_dir }}"
        owner: "{{ awx_user }}"
        group: "{{ awx_group }}"
        list_files: True
        remote_src: yes
      register: file_list
    - name: Run Ansible Galaxy
      command: >-
        {{ galaxy }} -p {{ project_dir }}/{{ file_list.files[1] }}/roles
        install -r {{ project_dir}}/{{ file_list.files[1] }}/roles/requirements.yml
        --force



